#!/usr/bin/python
# Copyright (c) 2010 Martin Ueding <dev@martin-ueding.de>

import os.path
import re
import subprocess

import prettytable

comments = [r"//", r"#", r"/\*", r"<--"]

keywords = ["TODO", "HACK", "FIXME", "XXX"]

def get_regex():
    return r"(%s)\s*(%s)" % ("|".join(comments), "|".join(keywords))

def main():
    grep_output = subprocess.check_output(["grep", "-RIEn", get_regex(), "."])

    grep_lines = grep_output.split("\n")

    findings = []

    for grep_line in grep_lines[:-1]:
        finding = []
        parts = grep_line.split(":", 2)
        finding.append(os.path.normpath(parts[0]))
        finding.append(int(parts[1]))
        m = re.match(r".*(%s)(.*)" % '|'.join(keywords), parts[2])
        if not m is None:
            finding.append(m.group(1).strip())
            finding.append(m.group(2).strip())


        findings.append(finding)

    files = {}
    for finding in findings:
        if not finding[0] in files:
            files[finding[0]] = []

        files[finding[0]].append(finding[1:])

    first = True

    for filename, tasks in files.items():
        if first:
            first = False
        else:
            print

        print filename
        prettytable.print_table(None, tasks)

if __name__ == "__main__":
    main()
