#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

cd "$HOME/public_html/git"

reponame="$1.git"

if [[ -d "$reponame" ]]
then
	echo "Notice: $reponame already exists."
fi

git init --bare "$reponame"

cd "$reponame/hooks"

mv post-update.sample post-update
