#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

version_regex="v(.+)"

destination="$1"

shift

cwd="$(pwd)"

for repo in "$@"
do
	project="$(basename "$repo")"
	cd "$cwd"

	cd "$repo"

	if [[ ! -d .git ]]
	then
		echo "Warning: $repo is not a git repository, skipping…"
		continue
	fi

	tags=$(git tag)

	if [[ -z "$tags" ]]
	then
		echo "Warning: $project has no tags, skipping…"
		continue
	fi

	for tag in $tags
	do
		if [[ $tag =~ $version_regex ]]
		then
			version="${BASH_REMATCH[1]}"

			tarball="$destination/$project/${project}_$version.tar"

			# If the tarball already exists, there is no need to recreate it.
			if [[ -f "$tarball" ]]
			then
				continue
			fi

			echo "Creating tarball for $version…"

			mkdir -p "$destination/$project/"

			git archive --prefix="$project-$version/" $tag | gzip > $tarball
		fi
	done
done
