#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

repo="$1"

curl -u "$(git config github.user):$(git config github.password)" https://api.github.com/user/repos -d "{\"name\":\"${repo}\"}"
