#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 2 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.

set -e
set -u

tarball_dir="$(git config --get tarball.destdir)"
tarball_ftp="$(git config --get tarball.ftp)"

filter_regex='.*_[0-9\.]+\.tar\.gz'

cd "$tarball_dir/"

for project in */
do
	cd "$tarball_dir/$project"

	echo "$project"

	for tarball in *.tar.gz
	do
		if [[ ! "$tarball" =~ $filter_regex ]]
		then
			continue
		fi

		curl --netrc --ftp-create-dirs --upload-file "$tarball" "$tarball_ftp$project"
	done
done
