#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

version_regex="v([\d\.]+)"

destination="$1"

shift

cwd="$(pwd)"

for repo in "$@"
do
	cd "$cwd"

	cd "$repo"

	if [[ ! -d .git ]]
	then
		echo "Warning: $repo is not a git repository, skipping…"
		continue
	fi

	tags=$(git tag)

	if [[ -z "$tags" ]]
	then
		echo "Warning: $repo has no tags, skipping…"
		continue
	fi

	for tag in $tags
	do
		echo "Processing $tag…"

		if [[ $tag =~ $version_regex ]]
		then
			version="${BASH_REMATCH[1]}"
		fi
	done
done
