#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 2 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.

set -e
set -u

version_regex="v(.+)"

destination="$(git config --get tarball.destdir)"

cwd="$(pwd)"

archive-tags() {
	project="$1"

	echo "$project"

	tags=$(git tag)

	if [[ -z "$tags" ]]
	then
		echo "Warning: $project has no tags, skipping…"
		continue
	fi

	for tag in $tags
	do
		if [[ $tag =~ $version_regex ]]
		then
			version="${BASH_REMATCH[1]}"

			tarball="$destination/$project/${project}_$version.tar.gz"

			# If the tarball already exists, there is no need to recreate it.
			if [[ -f "$tarball" ]]
			then
				continue
			fi

			echo "Creating tarball for $version…"

			mkdir -p "$destination/$project/"

			git archive --prefix="$project-$version/" $tag | gzip > $tarball
		fi
	done
}

if [[ -z "${1:-}" ]]
then
	topdir="$(git rev-parse --show-toplevel)"
	project="$(basename "$topdir")"

	archive-tags "$project"

else
	for repo in "$@"
	do
		project="$(basename "$repo")"
		cd "$cwd"

		cd "$repo"

		if [[ ! -d .git ]]
		then
			echo "Warning: $repo is not a git repository, skipping…"
			continue
		fi

		archive-tags "$project"

	done
fi
