#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

import argparse
import urllib.request
import json

__docformat__ = "restructuredtext en"

def main():
    options = _parse_args()

    filename, header = urllib.request.urlretrieve("https://api.github.com/users/martin-ueding/repos")
    with open(filename) as fp:
        repos = json.load(fp)

    names = [repo["name"] for repo in repos]

    names.sort()

    for name in names:
        print(name)

    print()
    print("Total: ", len(repos))


def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    #parser.add_argument("args", metavar="N", type=str, nargs="*", help="Positional arguments.")
    #parser.add_argument("", dest="", type="", default=, help=)
    #parser.add_argument("--version", action="version", version="<the version>")

    return parser.parse_args()


if __name__ == "__main__":
    main()
