#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 2 of the License, or (at your option) any later
# version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.

# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.

set -e
set -u

###############################################################################
#                              helper functions                               #
###############################################################################

check() {
	check-changelog
	check-makefile
	check-readme
	check-scm
	check-tags
	check-github
	check-chaos
}

_check-for-glob() {
	if [[ -n "$(find . -maxdepth 1 -name "$1" -print -quit)" ]]
	then
		return 0
	else
		return 1
	fi
}

###############################################################################
#                                   checks                                    #
###############################################################################

check-readme() {
	if ! _check-for-glob "README*" && ! _check-for-glob "readme*"
	then
		echo "no-readme"
	fi
}

check-changelog() {
	if ! _check-for-glob "CHANGELOG*" && ! _check-for-glob "changelog*"
	then
		echo "no-changelog"
	fi
}

check-scm() {
	for dir in .git .bzr .svn .hg
	do
		if [[ -d "$dir" ]]
		then
			return 0
		fi
	done

	echo "no-scm"
}

check-tags() {
	if [[ -d .git && -z "$(git tag)" ]]
	then
		echo "no-tags"
	fi
}

check-makefile() {
	if [[ ! -f makefile && ! -f Makefile ]]
	then
		echo "no-makefile"
		return 0
	fi

	if ! grep -E '^install:' [Mm]akefile > /dev/null
	then
		echo "no-make-install"
	fi

	if ! grep -E '^clean:' [Mm]akefile > /dev/null
	then
		echo "no-make-clean"
	fi
}

# Check whether this project is on GitHub.
check-github() {
	dir="$(pwd)"
	name="${dir##*/}"
	if ! wget "https://github.com/martin-ueding/$name" -O /dev/null &> /dev/null
	then
		echo "no-github"
	fi
}

# Check whether this project is on chaos.
check-chaos() {
	dir="$(pwd)"
	name="${dir##*/}"
	if ! wget "http://chaos.stw-bonn.de/users/mu/git/$name.git" -O /dev/null &> /dev/null
	then
		echo "no-chaos"
	fi
}

check
