#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

###############################################################################
#                              helper functions                               #
###############################################################################

check() {
	check-changelog &
	check-chaos &
	check-copying &
	check-github &
	check-makefile &
	check-package &
	check-ppa &
	check-readme &
	check-scm &
	check-tags &
	check-untagged-commits &
	check-website &
	wait
}

_check-for-glob() {
	if [[ -n "$(find . -maxdepth 1 -name "$1" -print -quit)" ]]
	then
		return 0
	else
		return 1
	fi
}

###############################################################################
#                                   checks                                    #
###############################################################################

check-changelog() {
	if ! _check-for-glob "CHANGELOG*" && ! _check-for-glob "changelog*"
	then
		echo "no-changelog"
	fi
}

# Check whether this project is on chaos.
check-chaos() {
	dir="$(pwd)"
	name="${dir##*/}"
	if ! wget "http://chaos.stw-bonn.de/users/mu/git/$name.git" -O /dev/null &> /dev/null
	then
		echo "no-chaos"
	fi
}

check-copying() {
	if ! _check-for-glob "COPYING*" && ! _check-for-glob "COPYING*"
	then
		echo "no-copying"
	fi
}

# Check whether this project is on GitHub.
check-github() {
	dir="$(pwd)"
	name="${dir##*/}"
	if ! wget "https://github.com/martin-ueding/$name" -O /dev/null &> /dev/null
	then
		echo "no-github"
	fi
}

check-makefile() {
	if [[ ! -f makefile && ! -f Makefile ]]
	then
		echo "no-makefile"
		return 0
	fi

	if ! grep -E '^install:' [Mm]akefile > /dev/null
	then
		echo "no-make-install"
	fi

	if ! grep -E '^clean:' [Mm]akefile > /dev/null
	then
		echo "no-make-clean"
	fi
}

check-package() {
	dir="$(pwd)"
	name="${dir##*/}"
	if ! cd "$HOME/Packaging/$name" &> /dev/null
	then
		echo "no-tar-archives"
	fi

	if [[ -z "$(find . -maxdepth 1 -type d -print -quit)" ]]
	then
		echo "no-package"
	fi
}

# Checks whether this project has a package in my Launchpad PPA.
check-ppa() {
	dir="$(pwd)"
	name="${dir##*/}"
	tempfile="$(mktemp)"
	wget -O "$tempfile" "https://launchpad.net/~martin-ueding/+archive/stable/+packages"  &> /dev/null

	if ! grep -F "$name" "$tempfile" &> /dev/null
	then
		echo "no-ppa"
	fi

	rm -f "$tempfile"
}

check-readme() {
	if ! _check-for-glob "README*" && ! _check-for-glob "readme*"
	then
		echo "no-readme"
	fi
}

check-scm() {
	for dir in .git .bzr .svn .hg
	do
		if [[ -d "$dir" ]]
		then
			return 0
		fi
	done

	echo "no-scm"
}

check-tags() {
	if [[ -d .git && -z "$(git tag)" ]]
	then
		echo "no-tags"
	fi
}

check-untagged-commits() {
	if ! git log --oneline --decorate master | head -n 1 | grep 'tag: '
	then
		echo 'untagged-commits'
	fi
}

# Check for a page on my personal homepage.
check-website() {
	dir="$(pwd)"
	name="${dir##*/}"
	if ! wget "http://martin-ueding.de/projects/$name/" -O /dev/null &> /dev/null
	then
		echo "no-website"
	fi
}

check
