#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

cd "$HOME/Branches"

outfile="$HOME/TODO/prolint-report.txt"

date > "$outfile"
echo > "$outfile"

for dir in */
do
	pushd "$dir"
	echo "${dir%/*}" >> "$outfile"
	prolint >> "$outfile"
	echo >> "$outfile"
	popd
done
