#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u


for repo in "$@"
do
	cd "$HOME/Branches/$repo"

	ssh chaos create-repo "$repo"

	git remote add chaos "chaos:public_html/git/$repo.git"

	git push chaos --all
done
