#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

for repo in "$@"
do
	repofolder="$HOME/Branches/$repo"

	if [[ ! -d "$repofolder" ]]
	then
		echo "Error: $repofolder does not exist. Skipping this repo."
		continue
	fi

	cd "$repofolder"

	ssh chaos create-bare "$repo"

	git remote add chaos "chaos:public_html/git/$repo.git"

	git push chaos --all
done
