#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

# Copies a given git repository onto a remote server. It is assumed that you
# have SSH access to the server.

set -e
set -u

server_alias=chaos

for repo in "$@"
do
	repofolder="$HOME/Branches/$repo"

	if [[ ! -d "$repofolder" ]]
	then
		echo "Error: $repofolder does not exist. Skipping this repo."
		continue
	fi

	if [[ ! -d "$repofolder/.git" ]]
	then
		echo "Error: $repofolder is not a git repo. Skipping this repo."
		continue
	fi

	cd "$repofolder"

	ssh chaos create-bare "$repo"

	if git remote | grep "$server_alias"
	then
		echo "Notice: $repo already has remote $server_alias."
	else
		git remote add "$server_alias" "chaos:public_html/git/$repo.git"
	fi

	git push "$server_alias" --all
done
