#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

import argparse

__docformat__ = "restructuredtext en"

def main():
    options = _parse_args()

    for filename in options.filenames:
        try:
            with open(filename) as f:
                line = next(f).strip()

                parts = line.split("/")

                program = parts[-1]

                if any([program == x for x in ["python", "python2"]]):
                    print(filename)
        except IOError:
            pass
        except UnicodeDecodeError:
            pass

def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("filenames", type=str, nargs="+", help="Positional arguments.")
    #parser.add_argument("", dest="", type="", default=, help=)
    #parser.add_argument("--version", action="version", version="<the version>")

    return parser.parse_args()


if __name__ == "__main__":
    main()
